backend:
  name: git-gateway
  branch: main

media_folder: 'static/images/uploads'

site_url: 'https://bobdauber.com'

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'static/posts'
    path: '{{slug}}/index'
    media_folder: 'images'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Material"
        name: "material"
        widget: "string"
      - label: "Cover Image"
        name: "cover_image"
        widget: "image"
        media_folder: "images/cover"
      - label: "Images"
        name: "images"
        widget: "image"
        allow_multiple: true