backend:
  name: git-gateway
  branch: main

publish_mode: simple
media_folder: 'static/uploads'

site_url: 'https://bobdauber.com'
display_url: 'https://bobdauber.com'

search: false
editor:
  preview: false

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'static/posts'
    path: '{{slug}}/index'
    media_folder: 'images'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Material"
        name: "material"
        widget: "string"
      - label: "Dimensions"
        name: "dimensions"
        widget: "object"
        fields:
          - {label: "Width", name: "width", widget: "number", value_type: "float"}
          - {label: "Height", name: "height", widget: "number", value_type: "float"}
          - {label: "Depth", name: "depth", widget: "number", value_type: "float"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "MMMM YYYY"
        date_format: "MMMM YYYY"
        picker_utc: true
      - label: "Cover Image"
        name: "cover_image"
        widget: "image"
        media_folder: "images/cover"
      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - label: "Description"
        name: "description"
        widget: "text"
  - name: 'about'
    label: 'About Page'
    files:
      - label: 'Bio'
        name: 'bio'
        file: 'static/about/bio.md'
        fields:
          - label: 'text'
            name: 'text'
            widget: 'text'